# -------------------------
# System & GUI Applications
# -------------------------
$browser = uwsm app -- zen-browser
$lock    = uwsm app -- hyprlock
$menu    = uwsm app -- fuzzel

# -------------------------
# Terminal Definitions
# -------------------------
$terminal          = uwsm app -- ghostty
$terminal_floating = $terminal --font-size=12

# -------------------------
# TUIs
# -------------------------
$about       = $terminal --class=about.com.mitchellh.ghostty
$anime       = $terminal --class=anime.com.mitchellh.ghostty -e ani-cli -q 1080p --dub
$music       = $terminal --class=cliamp.com.mitchellh.ghostty -e rmpc  

# -------------------------
# Floating TUIs
# -------------------------
$fileManager = $terminal --class=joshuto.com.mitchellh.ghostty -e joshuto
$opencode    = $terminal_floating --class=opencode.floating.com.mitchellh.ghostty -e opencode
$paru        = $terminal_floating --class=paru.com.mitchellh.ghostty -e pi
$btop        = $terminal_floating --class=btop.com.mitchellh.ghostty -e btop
