source = $HOME/.config/hypr/defaults.conf
source = $HOME/.config/hypr/keybindings.conf
source = $HOME/.config/hypr/input.conf
source = $HOME/.config/hypr/envs.conf
source = $HOME/.config/hypr/looknfeel.conf
source = $HOME/.config/hypr/windows.conf
