source = $HOME/.config/hypr/mocha.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = Monaspace Radon NF SemiBold

# GENERAL
general {
  hide_cursor = true
    no_fade_in = true
    no_fade_out = true
}

# BACKGROUND
background {
  monitor =
    path = ~/wallpapers/chill_cat_catppuccin.jpg
    blur_passes = 3
}

# TIME
label {
  monitor =
    text = $TIME
    color = $text
    font_size = 180
    font_family = $font
    position = 0, -100 
    halign = center
    valign = top
}

# DATE
label {
  monitor =
    text = cmd[update:43200000] date +"%A, %d %B %Y"
    color = $text
    font_size = 30
    font_family = $font
    position = 0, -380 
    halign = center
    valign = top
}

# FINGERPRINT
{
  monitor = "";
  text = "$FPRINTPROMPT";
  color = "$text";
  font_size = 14;
  font_family = $font;
  position = "0, -107";
  halign = "center";
  valign = "center";
}

# INPUT FIELD
input-field {
  monitor =
    size = 600, 100
    outline_thickness = 4
    border_radius = 0
    rounding = 0
    dots_size = 0
    dots_spacing = 0.2
    dots_center = true
    dots_rounding = -1
    outer_color = $accent
    inner_color = $surface0
    font_color = $text
    fade_on_empty = false
    placeholder_text = <span foreground="##$textAlpha"><i>Password</i></span>
    check_color = $accent
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 0, 0
    halign = center
    valign = center
}
