wallpaper {
  monitor = eDP-1
    # path = ~/wallpapers/chill_cat_catppuccin.jpg
    # path = ~/wallpapers/old_york.jpg
    # path = ~/wallpapers/peaceful_landscape_1.jpg
    path = ~/wallpapers/peaceful_landscape_2.jpg
    # path = ~/wallpapers/peaceful_landscape_3.jpg
    # path = ~/wallpapers/peaceful_landscape_4.jpg

    fit_mode = fit
}

splash = false
