general {
  # gaps_in = 4
  #   gaps_out = 4
  gaps_in = 0
    gaps_out = 0
    border_size = 2

    col.active_border = rgb(a6e3a1)
    col.inactive_border = rgb(cba6f7)

    layout = dwindle
}

xwayland {
  force_zero_scaling = true
}

render {
  cm_fs_passthrough = 0
}

decoration {
  rounding = 0
    inactive_opacity = 0.80

    blur {
      enabled = true
        size = 3
        passes = 3
    }
}

animations {
    enabled = false 
}

dwindle {
  pseudotile = true
    preserve_split = true
}

master {
  new_status = master
}

misc {
  force_default_wallpaper = 0
    disable_hyprland_logo = true
}
