general {
  gaps_in = 6
    gaps_out = 6
    border_size = 2

    col.active_border = rgb(cba6f7)
# col.inactive_border = rgb(f5e0dc)

    layout = dwindle
}

xwayland {
  force_zero_scaling = true
}

render {
  cm_fs_passthrough = 0
}

decoration {
  rounding = 0
    inactive_opacity = 0.80

    blur {
      enabled = true
        size = 3
        passes = 3
    }
}

animations {
  enabled = false
}

dwindle {
  pseudotile = true
    preserve_split = true
}

master {
  new_status = master
}

misc {
  force_default_wallpaper = 0
    disable_hyprland_logo = true
}
