# -------------------------
# Layer Rules
# -------------------------
layerrule {
  name = fuzzel_blur
    match:namespace = launcher
    blur = true
}

layerrule {
  name = waybar_blur
    match:namespace = waybar
    blur = true
}

# -------------------------
# Window Rules
# -------------------------

windowrule {
  name = opencode_float
    match:class = opencode.floating.com.mitchellh.ghostty
    size = 800 500
    center = true
    float = true
    pin = true
    opacity = 0.90
}

windowrule {
  name = about_float
    match:class = about.com.mitchellh.ghostty
    size = 800 350
    float = true
    center = true
}

windowrule {
  name = cliamp
    match:class = cliamp.com.mitchellh.ghostty
    xray = true
}

windowrule {
  name = anime_float
    match:class = anime.com.mitchellh.ghostty
    size = 800 300
    center = true
    float = true
    opacity = 0.90
}

windowrule {
  name = nemo_float
    match:class = nemo
    size = 1000 600
    center = true
    float = true
    opacity = 0.90
}

windowrule {
  name = mpv_fullscreen
    match:class = mpv
    fullscreen = true
}

windowrule {
  name = paru_float
    match:class = paru.com.mitchellh.ghostty
    size = 800 400
    center = true
    float = true
    pin = true
    opacity = 0.90
}

windowrule {
  name = joshuto_float
    match:class = joshuto.com.mitchellh.ghostty
    size = 1000 600
    center = true
    float = true
    opacity = 0.90
}

windowrule {
  name = impala_float
    match:class = impala.com.mitchellh.ghostty
    size = 1000 600
    center = true
    float = true
    pin = true
    opacity = 0.90
}

windowrule {
  name = wiremix_float
    match:class = wiremix.com.mitchellh.ghostty
    size = 1000 600
    center = true
    float = true
    pin = true
    opacity = 0.90
}

windowrule {
  name = btop_float
    match:class = btop.com.mitchellh.ghostty
    size = 1000 600
    center = true
    float = true
    pin = true
    opacity = 0.90
}
